FROM nginx:1.20-alpine

ENV TACTICAL_DIR /opt/tactical

RUN apk add --no-cache openssl bash

SHELL ["/bin/bash", "-e", "-o", "pipefail", "-c"]

COPY docker/containers/tactical-nginx/entrypoint.sh /docker-entrypoint.d/
RUN chmod +x /docker-entrypoint.d/entrypoint.sh

EXPOSE 443 80